### ISSUE TITLE
Bioconda package

### ISSUE THREAD

**Issue by winni2k** [Genomon-Project/EBFilter#11]
EBFilter could be packaged as a [bioconda package](https://bioconda.github.io/). That way the samtools requirement would be installed as well. In the mean time, here is my current conda environment.yml:

**UPDATE:** This environment.yml now appears to work

```
channels:
  - conda-forge
  - bioconda

dependencies:
  - samtools=1.10
  - pysam
  - numpy
  - scipy
  - vcfpy
  - pip
  - pip:
      - "git+https://github.com/Genomon-Project/EBFilter.git@v0.2.2#egg=ebfilter"
```

**Comment by friend1ws** [comment]
Dear @winni2k,
Thanks for the great feedback. We will consider making bioconda environments in the near future based on your suggestion.
