### ISSUE TITLE
Question: Can EBFilter handle indels?

### ISSUE THREAD

**Issue by messersc** [Genomon-Project/EBFilter#5]
Hi,

I know that EBcall is able to call indels, but can EBFilter also be used to filter indels from another caller?

Do I need to change the thresholds for filtering or rather are there any guidelines for this?

Thanks,
Clemens

**Comment by friend1ws** [comment]
Hi, thank you very much for the interest in EBFilter.
Yes, EBFilter can treat indels, and we think indel can be filtered properly using the same criteria as SNVs.

Please let me know if you have any additional questions.
Thank you.
Yuichi

**Comment by messersc** [comment]
Hi @friend1ws,

thank you for your advice. We have EBFilter now running for indels and will have a look at the results soon.

Best regards,
Clemens
