### ISSUE TITLE
Are results non-deterministic?

### ISSUE THREAD

**Issue by messersc** [Genomon-Project/EBFilter#7]
Dear maintainers,

I have a question about the reproducibility of results using EBfilter, which seem to be non-deterministic. We have run EBFilter on the same cohort twice and after filtering, we do see some larger differences for a few samples after applying the same threshold for the EBScore. Here's an example, with CHROM, POS and EB for the same input vcf from two runs:

```
1       566573  2.055                                         | 1       566573  2.059
1       569624  3.869                                         | 1       569624  3.863
1       776163  0.573                                         | 1       776163  0.575
1       1935912 2.452                                         | 1       1935912 2.575
1       2078817 2.969                                         | 1       2078817 1.564
```

While the difference in EBScore is not large for the first four entries, the fifth does not make the cut in the second run for our threshold. I can post more examples, but wanted to find out about the major sources for these changes first.

Obviously, the panel of normals do have an impact, but we used the same 25 bams for both runs.
Are there any other variables influencing the EBscore?

Best regards,
Clemens

**Comment by friend1ws** [comment]
Thanks for the interest in EBFilter.
When you performed EBFilter twice, did you changed computational environment or software versions (e.g., samtools, numpy)? Since EBFilter depends on several packages such as samtools and numpy, the difference of versions of these software can changes the result. Otherwise, I think EBFilter should produce the same value...

**Comment by messersc** [comment]
Hi @friend1ws,

thanks for the quick response. The analyses were run by two different people and we not compared our conda environments and indeed, there are differences like you suggested:

Run 1:
```
samtools                  1.7                           1    bioconda                                                                                                                        
pysam                     0.14.0          py27_htslib1.7_2    bioconda                                                                                                                       
numpy                     1.14.1           py27h3dfced4_1
```

Run 2:
```
samtools                  1.5                           1    bioconda
pysam                     0.11.2.2                 py27_1    bioconda
numpy                     1.14.0           py27h3dfced4_1
```

I tried to find which versions of the respective tools are recommended for EBFilter, but I didn't see anything. The bioconda recipe also does not pin any versions for the dependencies.

What to you think is the best course of action here?
Clemens

**Comment by friend1ws** [comment]
Sorry for late response.
Yes. I think the differences in versions of samtools and pysam can change the result.

The setting we are using is quite old.
```
samtools 1.2
pysam 0.9.1.4
numpy 1.11.2
```
This seems working not so bad. 
But I think new adopters tend to use the up-to-date version of each software.
So I would like to try to evaluate the result using the combinations of upgrading most recent versions,
and see the compare the result in near future.
Thank you very much for the important feedback any way.
